// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VallejosDayana_Examen1.Data;

#nullable disable

namespace VallejosDayana_Examen1.Migrations
{
    [DbContext(typeof(VallejosDayana_Examen1Context))]
    partial class VallejosDayana_Examen1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VallejosDayana_Examen1.Models.Celular", b =>
                {
                    b.Property<int>("IdCelular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCelular"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int?>("dVallejosId")
                        .HasColumnType("int");

                    b.HasKey("IdCelular");

                    b.HasIndex("dVallejosId");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("VallejosDayana_Examen1.Models.DVallejos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("EsSoltero")
                        .HasColumnType("bit");

                    b.Property<double>("Estatura")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DVallejos");
                });

            modelBuilder.Entity("VallejosDayana_Examen1.Models.Celular", b =>
                {
                    b.HasOne("VallejosDayana_Examen1.Models.DVallejos", "dVallejos")
                        .WithMany()
                        .HasForeignKey("dVallejosId");

                    b.Navigation("dVallejos");
                });
#pragma warning restore 612, 618
        }
    }
}
